title: Ben Corcoran Data Analyst
description:  # this means to ignore newlines until "baseurl:"

permalink: ':title/'
baseurl: "" # the subpath of your site, e.g. /blog
url: "www.benjamincorcoran.com" # the base hostname & protocol for your site, e.g. http://example.com
site-twitter: #if your site has a twitter account, enter it here

# Author Settings
author: Ben Corcoran # add your name
author-img: https://s.gravatar.com/avatar/49266cade85fd1b32e3896a9c56fa78c?s=80# add your photo
about-author: Data Analyst? 
social-twitter: benjcorc # add your Twitter handle
social-medium: benjamin.corcoran # add your Facebook handle
social-github: benjamincorcoran # add your Github handle
social-linkedin: ben-corcoran-a0a229100 # add your Linkedin handle
social-email: mail@benjamincorcoran.com # add your Email address

# Disqus
discus-identifier: # add your discus identifier

# Tracker
analytics: # Google Analytics

# Build Settings
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji


# Paginate settings
paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
